--DROP TABLE AULA CASCADE CONSTRAINTS;

--DROP TABLE RESPONSABLE CASCADE CONSTRAINTS;

--DROP TABLE RESERVA CASCADE CONSTRAINTS;

--DROP TABLE RESERVA_PUNTUAL CASCADE CONSTRAINTS;

--DROP TABLE RESERVA_PERIODICA CASCADE CONSTRAINTS;

--DROP TABLE PROFESOR CASCADE CONSTRAINTS;

--DROP TABLE ASIGNATURAS CASCADE CONSTRAINTS;

--DROP TABLE ASIGNATURA_PROFESOR CASCADE CONSTRAINTS;

--DROP TABLE GRADO CASCADE CONSTRAINTS;

--DROP TABLE GRUPO CASCADE CONSTRAINTS;

--DROP TABLE CURSO CASCADE CONSTRAINTS;

--DROP TABLE SEMESTRE CASCADE CONSTRAINTS;

--DROP TABLE DIA CASCADE CONSTRAINTS;

--DROP TABLE LECTIVO CASCADE CONSTRAINTS;

--DROP TABLE CAMBIO_DOCENCIA CASCADE CONSTRAINTS;

--DROP TABLE EXAMEN CASCADE CONSTRAINTS;

--DROP TABLE FESTIVO CASCADE CONSTRAINTS;



CREATE TABLE AULA(
    NOMBRE VARCHAR(20) PRIMARY KEY,
    EDIFICIO VARCHAR(6),
    PLANTA NUMERIC(1),
    CAPACIDAD NUMERIC(3) CHECK (CAPACIDAD >= 0),
    NUM_ORDENADORES NUMERIC(2) CHECK(NUM_ORDENADORES >= 0),
    ALTAVOCES BOOLEAN NOT NULL DEFAULT FALSE,
    PROYECTOR BOOLEAN NOT NULL DEFAULT FALSE,
    CAMARA BOOLEAN NOT NULL DEFAULT FALSE,
    ENCHUFES BOOLEAN,   --Mirar si la cantidad o que referencias tener
    M2 NUMERIC (4,2) CHECK(M2 >= 0),
    OTROS VARCHAR(30)
);

CREATE TABLE RESPONSABLE(
    CORREO VARCHAR(30) PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(30) NOT NULL,
    TELEFONO NUMERIC(9),
    CODIGO_DOCENTE VARCHAR(9) UNIQUE REFERENCES DOCENTE(CODIGO) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE RESERVA(
    IDRESERVA VARCHAR(5) PRIMARY KEY,
    NOMBRE_AULA VARCHAR(8) NOT NULL REFERENCES AULA(NOMBRE) ON UPDATE CASCADE ON DELETE CASCADE,
    ID_DIA DATE NOT NULL REFERENCES DIA(DIA) ON UPDATE CASCADE ON DELETE CASCADE,
    MOMENTO_RESERVA TIMESTAMP NOT NULL DEFAULT NOW(),
    ESTADO CHAR(1),
    TIPO CHAR(1),
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    CHECK (HORA_FIN > HORA_INICIO)
);

CREATE TABLE RESERVA_PUNTUAL (
    ID_RESERVA  VARCHAR(12) PRIMARY KEY REFERENCES RESERVA(IDRESERVA) ON UPDATE CASCADE ON DELETE CASCADE,
    ID_RESPONSABLE VARCHAR(9) NOT NULL REFERENCES RESPONSABLE(CORREO) ON UPDATE CASCADE ON DELETE CASCADE,
    --ID_ASIGNATURA VARCHAR(10) REFERENCES ASIGNATURAS(ID_ASIGNATURA) ON UPDATE CASCADE ON DELETE CASCADE,
    MOTIVO VARCHAR(90),
    INICIO TIMESTAMPTZ NOT NULL,
    FIN TIMESTAMPTZ NOT NULL,
    CHECK (FIN > INICIO)
);

CREATE TABLE RESERVA_PERIODICA (
    ID_RESERVA       VARCHAR(12) PRIMARY KEY REFERENCES RESERVA(IDRESERVA) ON UPDATE CASCADE ON DELETE CASCADE,
    ID_ASIGNATURA VARCHAR(10) NOT NULL REFERENCES ASIGNATURAS(IDASIGNATURA) ON UPDATE CASCADE ON DELETE CASCADE,
    DIA_SEMANA       SMALLINT NOT NULL CHECK (DIA_SEMANA BETWEEN 1 AND 7), -- 1=Lunes..7=Domingo (ISO)
    FECHA_INICIO     DATE NOT NULL, -- PUEDE SER QUE NO HAGA FALTA YA QUE SE PUEDE SACAR DE LA FECHA DEL SEMESTRE
    FECHA_FIN        DATE NOT NULL,
    INTERVALO_SEMANAS SMALLINT NOT NULL DEFAULT 1 CHECK (INTERVALO_SEMANAS >= 1),
    CHECK (FECHA_FIN >= FECHA_INICIO)
);


CREATE TABLE DOCENTE(
    CODIGO VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    CORREO VARCHAR(30) NOT NULL,
    TELEFONO VARCHAR(9)
);

CREATE TABLE ASIGNATURAS(
    IDASIGNATURA VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    ABREVIATURA VARCHAR(20),
    CURSO_GRADO NUMERIC(1) NOT NULL CHECK(CURSO_GRADO BETWEEN 1 AND 6),
    SEMESTRE_ACADEMICO NUMERIC(1) NOT NULL CHECK(SEMESTRE_ACADEMICO IN(1,12)),  -- Se denominan los semestres también en función del año en el que se enuentran
    ECTS NUMERIC(2) NOT NULL CHECK(ECTS >= 0),
    GRADO_ID VARCHAR(10) NOT NULL REFERENCES GRADO(IDGRADO) ON UPDATE CASCADE ON DELETE CASCADE,
    TIPO CHAR(1),   --Para saber si es una obligatoria o es optativa
    HORAS_PRACTICAS NUMERIC(1)
);

CREATE TABLE IMPARTE(
    CODIGO_DOCENTE VARCHAR(9) NOT NULL REFERENCES PROFESOR(CODIGO) ON UPDATE CASCADE ON DELETE CASCADE,
    ID_ASIGNATURA VARCHAR(10) NOT NULL REFERENCES ASIGNATURAS(IDASIGNATURA) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY(DNI_PROFESOR, ID_ASIGNATURA)
);

CREATE TABLE GRADO(
    IDGRADO VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    ABREVIATURA VARCHAR(20) NOT NULL,
    COORDINADOR VARCHAR(30)
);


-- Ver la relación entre asignaturas y grupos para saber si añadir una tabla más o sólo clave foránea y ver qué atributos hacen falta
CREATE TABLE GRUPO(
    GRUPOID VARCHAR(10) PRIMARY KEY,
    NOMBRE CHAR(3),
    ID_ASIGNATURA VARCHAR(10) NOT NULL REFERENCES ASIGNATURAS(IDASIGNATURA) ON UPDATE CASCADE ON DELETE CASCADE
);



CREATE TABLE CURSO(
    IDCURSO VARCHAR(10) PRIMARY KEY,    -- 2025-2026
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL
);

CREATE TABLE SEMESTRE(
    IDSEMESTRE VARCHAR(10) PRIMARY KEY,
    CURSO_ID VARCHAR(10) NOT NULL REFERENCES CURSO(IDCURSO) ON UPDATE CASCADE ON DELETE CASCADE,
    NUMERO NUMERIC(1) CHECK(NUMERO IN(1,2)),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL
);

CREATE TABLE DIA(
    DIA DATE PRIMARY KEY,
    ID_SEMESTRE VARCHAR(10) NOT NULL REFERENCES SEMESTRE(IDSEMESTRE) ON UPDATE CASCADE ON DELETE CASCADE,
    DIA_SEMANA NUMERIC CHECK(DIA_SEMANA BETWEEN 1 AND 5)

);

CREATE TABLE LECTIVO(
    ID_DIA DATE PRIMARY KEY,
    FOREIGN KEY(ID_DIA) REFERENCES DIA(DIA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CAMBIO_DOCENCIA(
    ID_DIA DATE PRIMARY KEY,
    SUSTITUYE_DIA NUMERIC CHECK(SUSTITUYE_DIA BETWEEN 1 AND 5)   --VER SI ASÍ BIEN TRATADO O BUSCAR OTRA FORMA
    FOREIGN KEY(ID_DIA) REFERENCES DIA(DIA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE EXAMEN(
    ID_DIA DATE PRIMARY KEY,
    CONVOCATORIA NUMERIC(1) CHECK(CONVOCATORIA IN(1,2)),
    FOREIGN KEY(ID_DIA) REFERENCES DIA(DIA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE FESTIVO(
    ID_DIA DATE PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ALCANCE VARCHAR(10),
    FOREIGN KEY(ID_DIA) REFERENCES DIA(DIA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TFG(
    ID_DIA DATE PRIMARY KEY,
    CONVOCATORIA NUMERIC(1) CHECK(CONVOCATORIA IN(1,2)),
    FOREIGN KEY(ID_DIA) REFERENCES DIA(DIA) ON UPDATE CASCADE ON DELETE CASCADE
);



