# Generated by Django 5.2.8 on 2025-11-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia', models.DateField(db_column='DIA', primary_key=True, serialize=False)),
                ('dia_semana', models.DecimalField(blank=True, db_column='DIA_SEMANA', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.CharField(db_column='IDCURSO', max_length=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateField(db_column='FECHA_FIN')),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('idsemestre', models.CharField(db_column='IDSEMESTRE', max_length=10, primary_key=True, serialize=False)),
                ('numero', models.DecimalField(blank=True, db_column='NUMERO', decimal_places=0, max_digits=1, null=True)),
                ('fecha_inicio', models.DateField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateField(db_column='FECHA_FIN')),
            ],
            options={
                'db_table': 'semestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CambioDocencia',
            fields=[
                ('id_dia', models.OneToOneField(db_column='ID_DIA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calendario.dia')),
                ('sustituye_dia', models.DecimalField(blank=True, db_column='SUSTITUYE_DIA', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cambio_docencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_dia', models.OneToOneField(db_column='ID_DIA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calendario.dia')),
                ('convocatoria', models.DecimalField(blank=True, db_column='CONVOCATORIA', decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'examen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Festivo',
            fields=[
                ('id_dia', models.OneToOneField(db_column='ID_DIA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calendario.dia')),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=50, null=True)),
                ('alcance', models.CharField(blank=True, db_column='ALCANCE', max_length=10, null=True)),
            ],
            options={
                'db_table': 'festivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectivo',
            fields=[
                ('id_dia', models.OneToOneField(db_column='ID_DIA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calendario.dia')),
            ],
            options={
                'db_table': 'lectivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tfg',
            fields=[
                ('id_dia', models.OneToOneField(db_column='ID_DIA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calendario.dia')),
                ('convocatoria', models.DecimalField(blank=True, db_column='CONVOCATORIA', decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'tfg',
                'managed': False,
            },
        ),
    ]
