# Generated by Django 5.2.8 on 2025-11-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('nombre', models.CharField(db_column='NOMBRE', max_length=20, primary_key=True, serialize=False)),
                ('edificio', models.CharField(blank=True, db_column='EDIFICIO', max_length=6, null=True)),
                ('planta', models.DecimalField(blank=True, db_column='PLANTA', decimal_places=0, max_digits=1, null=True)),
                ('capacidad', models.DecimalField(blank=True, db_column='CAPACIDAD', decimal_places=0, max_digits=3, null=True)),
                ('num_ordenadores', models.DecimalField(blank=True, db_column='NUM_ORDENADORES', decimal_places=0, max_digits=2, null=True)),
                ('altavoces', models.BooleanField(db_column='ALTAVOCES')),
                ('proyector', models.BooleanField(db_column='PROYECTOR')),
                ('camara', models.BooleanField(db_column='CAMARA')),
                ('enchufes', models.BooleanField(blank=True, db_column='ENCHUFES', null=True)),
                ('m2', models.DecimalField(blank=True, db_column='M2', decimal_places=2, max_digits=4, null=True)),
                ('otros', models.CharField(blank=True, db_column='OTROS', max_length=30, null=True)),
                ('semestre_academico', models.DecimalField(blank=True, db_column='SEMESTRE_ACADEMICO', decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'aula',
                'managed': False,
            },
        ),
    ]
