# Generated by Django 5.2.8 on 2026-06-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'managed': False, 'permissions': [('view_ocupacion_aula', 'Can view occupation of aula')]},
        ),
    ]
