# Generated by Django 5.2.8 on 2025-11-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.CharField(db_column='IDRESERVA', max_length=5, primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(db_column='NOMBRE_AULA', max_length=8)),
                ('momento_reserva', models.DateTimeField(db_column='MOMENTO_RESERVA')),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=1, null=True)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=1, null=True)),
                ('capacidad_solicitada', models.IntegerField(blank=True, db_column='CAPACIDAD_SOLICITADA', max_length=3, null=True)),
                ('hora_inicio', models.TimeField(db_column='HORA_INICIO')),
                ('hora_fin', models.TimeField(db_column='HORA_FIN')),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('correo', models.CharField(db_column='CORREO', max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=20)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=30)),
                ('telefono', models.DecimalField(blank=True, db_column='TELEFONO', decimal_places=0, max_digits=9, null=True)),
                ('codigo_docente', models.CharField(blank=True, db_column='CODIGO_DOCENTE', max_length=9, null=True, unique=True)),
            ],
            options={
                'db_table': 'responsable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaPeriodica',
            fields=[
                ('id_reserva', models.OneToOneField(db_column='ID_RESERVA', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservas.reserva')),
                ('dia_semana', models.SmallIntegerField(db_column='DIA_SEMANA')),
                ('fecha_inicio', models.DateField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateField(db_column='FECHA_FIN')),
                ('intervalo_semanas', models.SmallIntegerField(db_column='INTERVALO_SEMANAS')),
            ],
            options={
                'db_table': 'reserva_periodica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaPuntual',
            fields=[
                ('id_reserva', models.OneToOneField(db_column='ID_RESERVA', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservas.reserva')),
                ('motivo', models.CharField(blank=True, db_column='MOTIVO', max_length=90, null=True)),
                ('inicio', models.DateTimeField(db_column='INICIO')),
                ('fin', models.DateTimeField(db_column='FIN')),
            ],
            options={
                'db_table': 'reserva_puntual',
                'managed': False,
            },
        ),
    ]
