# Generated by Django 5.2.8 on 2026-01-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True},
        ),
    ]
