# Generated by Django 5.2.8 on 2026-01-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False},
        ),
    ]
