# Generated by Django 5.2.8 on 2026-06-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservapuntual',
            options={'managed': False, 'permissions': [('request_reserv_puntual', 'Can request reserva puntual')]},
        ),
    ]
