# Generated by Django 5.2.8 on 2026-06-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reservapuntual_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservapuntual',
            options={'managed': False, 'permissions': [('request_reserv_puntual', 'Can request reserva puntual'), ('change_estado_reserva_puntual', 'Can change estado of reserva puntual'), ('view_own_reserva_puntual', 'Can view own reserva puntual'), ('view_own_reserva', 'Can view own reserva'), ('import_horario', 'Can import horario')]},
        ),
    ]
