# Generated by Django 5.2.8 on 2026-05-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('idasignatura', models.CharField(db_column='IDASIGNATURA', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=30)),
                ('abreviatura', models.CharField(blank=True, db_column='ABREVIATURA', max_length=20, null=True)),
                ('curso_grado', models.DecimalField(db_column='CURSO_GRADO', decimal_places=0, max_digits=1)),
                ('semestre_academico', models.DecimalField(db_column='SEMESTRE_ACADEMICO', decimal_places=0, max_digits=1)),
                ('ects', models.DecimalField(db_column='ECTS', decimal_places=0, max_digits=2)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=1, null=True)),
                ('horas_practicas', models.DecimalField(blank=True, db_column='HORAS_PRACTICAS', decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'asignaturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=30)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=100)),
                ('correo', models.CharField(db_column='CORREO', max_length=30)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=9, null=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('idgrado', models.CharField(db_column='IDGRADO', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=80)),
                ('abreviatura', models.CharField(db_column='ABREVIATURA', max_length=20)),
                ('coordinador', models.CharField(blank=True, db_column='COORDINADOR', max_length=30, null=True)),
            ],
            options={
                'db_table': 'grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grupoid', models.AutoField(db_column='GRUPOID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=3, null=True)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'imparte',
                'managed': False,
            },
        ),
    ]
